### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by nate8199** [lvenier/node-red-contrib-discordjs#1]
Is there a way to push a file as an attachment with this?  I had it working with node-red-contrib-discord, but it doesn't work with this newer node.
https://github.com/jorisvddonk/node-red-contrib-discord/issues/8
This is the function node I used before.
Flow is a http request > file > function > discordjs
the file is writing the picture to disk properly, but its not sending past this function node, I have tried changing it to no avail.

```
var channel = msg.channel.id;
var t = msg.topic;
msg = {payload: "Here it is!", attachment:"/home/pi/trend.png", channel: {id : channel}};
msg.topic = ""+t+"";
node.status({fill:"green", shape:"ring", text:"sent"});
node.send([msg]);
```

**Comment by lvenier** [comment]
I'll have a look later today and add this if easy fix.

**Comment by lvenier** [comment]
Attachment class renamed MessageAttachment as per discord v12

**Comment by nate8199** [comment]
This works now with my original function code from above after I updated the node in the palette and restarted node-red.

Here is the 4 nodes I use if interested;
Function > http Request > File node > Function, then it goes out to Discord sendMessage


`[{"id":"45f82348.17826c","type":"function","z":"4bda7ab4.bb49a4","name":"send","func":"var channel = msg.channel.id;\nvar t = msg.topic;\nmsg = {payload: \"Here it is!\", attachment: \"/home/pi/trend.png\", channel: {id : channel}};\nmsg.topic = \"\"+t+\"\";\n\nnode.status({fill:\"green\", shape:\"ring\", text:\"sent\"});\nnode.send([msg]);","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":750,"y":180,"wires":[[]]},{"id":"1af129e7.06c986","type":"file","z":"4bda7ab4.bb49a4","name":"","filename":"/home/pi/trend.png","appendNewline":false,"createDir":false,"overwriteFile":"true","encoding":"none","x":570,"y":180,"wires":[["45f82348.17826c"]]},{"id":"fca7c4c3.71e638","type":"http request","z":"4bda7ab4.bb49a4","name":"","method":"GET","ret":"bin","url":"","tls":"","x":360,"y":180,"wires":[["1af129e7.06c986"]]},{"id":"154644b4.65d41b","type":"function","z":"4bda7ab4.bb49a4","name":"Panel_Name","func":"//IP address to Grafana\nvar ip = '10.10.10.10';\n//trend image width\nvar w = 1000;\n//trend image height\nvar h = 500;\n//time zone\nvar tz = 'America/Denver'\n\nvar channel = msg.channel.id;\n// I set the time in a previous change node, it is the time frame for the trend, typically 24h or 2d\nvar time = msg.payload;\nvar l = \"Panel Name\";\nvar t = msg.topic;\nvar c = msg.channel.id;\nmsg.header = {\n    Authorization: 'Bearer PASTE_YOUR_GRAFANA_API_KEY_HERE'\n    };\n    \n// You can get this URL by sharing a trend panel, and clicking the Direct link rendered image at the bottom\n// I am using Docker to run Grafana and Grafana-image-renderer to make these trend images\n\nmsg.url = 'http://'+ip+':3000/render/d-solo/7ZMH58m7z/panel_name?orgId=1&from-'+time+'&to=now&panelId=2&width='+w+'&height='+h+'&tz='+tz+'';\nmsg.time = \"\"+time+\"\";\nmsg.payload = \"\"+l+\"\";\nmsg.topic = \"\"+t+\"\";\n\nnode.send([msg]);\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":190,"y":180,"wires":[["fca7c4c3.71e638"]]}]`
